<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 3" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="/home/hieu/Documents/AI/Machine learning/KNN2MNist.py" status="error" test="KNN2MNist" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "/home/hieu/Documents/eclipse/plugins/org.python.pydev.core_6.4.4.201807281807/pysrc/_pydev_runfiles/pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "/home/hieu/Documents/AI/Machine learning/KNN2MNist.py", line 15, in <module>
    mndata.load_testing()
  File "/home/hieu/.local/lib/python2.7/site-packages/mnist/loader.py", line 117, in load_testing
    os.path.join(self.path, self.test_lbl_fname))
  File "/home/hieu/.local/lib/python2.7/site-packages/mnist/loader.py", line 247, in load
    with self.opener(path_lbl, 'rb') as file:
  File "/home/hieu/.local/lib/python2.7/site-packages/mnist/loader.py", line 239, in opener
    return open(path_fn, *args, **kwargs)
IOError: [Errno 2] No such file or directory: '../home/hieu/Documents/AI/Machine learning/MNIST/t10k-labels-idx1-ubyte'
ERROR: Module: KNN2MNist could not be imported (file: /home/hieu/Documents/AI/Machine learning/KNN2MNist.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Machine learning KNN2MNist.py (1) [pyunit run]"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
